name: Build Chocolatey Packages

on:
 # push:
 #   branches:
 #     - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Read and Increment Version
      id: version
      run: |
        $version = Get-Content VERSION
        $parts = $version.Split('.')
        $patch = [int]$parts[2] + 1
        $newVersion = "$($parts[0]).$($parts[1]).$patch"
        Set-Content VERSION $newVersion
        echo "version=$newVersion" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
      shell: pwsh

    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
        if (-not (Test-Path "C:\ProgramData\Chocolatey")) {
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
        }
      shell: pwsh

    - name: Create dist Directory
      run: |
        New-Item -ItemType Directory -Path ./dist -Force
      shell: pwsh

    - name: Build Scrutiny Package
      run: |
        if (-not (Test-Path ./packages/scrutiny/scrutiny.nuspec)) { throw "scrutiny.nuspec not found" }
        choco pack ./packages/scrutiny/scrutiny.nuspec --outputdirectory ./dist
        if (-not (Test-Path ./dist/scrutiny.*.nupkg)) { throw "Scrutiny package not created" }
      shell: pwsh

    - name: Build ExplorerPatcher Package
      run: |
        if (-not (Test-Path ./packages/explorerpatcher/explorerpatcher.nuspec)) { throw "explorerpatcher.nuspec not found" }
        choco pack ./packages/explorerpatcher/explorerpatcher.nuspec --outputdirectory ./dist
        if (-not (Test-Path ./dist/explorerpatcher.*.nupkg)) { throw "ExplorerPatcher package not created" }
      shell: pwsh

    - name: Publish to Repository Feed
      run: |
        New-Item -ItemType Directory -Path ./packages/feed -Force
        Copy-Item -Path ./dist/*.nupkg -Destination ./packages/feed
        $timestamp = Get-Date -Format o
        $feed = '<?xml version="1.0" encoding="utf-8"?>
        <feed xml:base="https://raw.githubusercontent.com/LostOnTheLine/choco-github-packages/main/packages/feed" xmlns="http://www.w3.org/2005/Atom">
          <title>LostOnTheLine Chocolatey Packages</title>
          <id>https://raw.githubusercontent.com/LostOnTheLine/choco-github-packages/main/packages/feed</id>
          <updated>' + $timestamp + '</updated>
          <link rel="self" href="https://raw.githubusercontent.com/LostOnTheLine/choco-github-packages/main/packages/feed" />
          {0}
        </feed>'
        $entries = ""
        $nupkgs = Get-ChildItem -Path ./packages/feed -Filter *.nupkg
        foreach ($nupkg in $nupkgs) {
          $id = $nupkg.BaseName.Split('.')[0]
          $version = $nupkg.BaseName -replace '^[^\.]*\.',''
          $entries += "<entry>
            <id>$id.$version</id>
            <title>$id</title>
            <updated>$timestamp</updated>
            <content type=""application/zip"" src=""$($nupkg.Name)"" />
          </entry>"
        }
        $feed = [string]::Format($feed, $entries)
        Set-Content -Path ./packages/feed/Packages -Value $feed
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add packages/feed
        git commit -m "Update feed with packages v${{ steps.version.outputs.version }}"
        git push
      shell: pwsh

    - name: Commit Updated VERSION
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add VERSION
        git commit -m "Bump version to ${{ steps.version.outputs.version }}"
        git push
      shell: bash