name: Build Chocolatey Packages

on:
 # push:
 #   branches:
 #     - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Read and Increment Version
      id: version
      run: |
        $version = Get-Content VERSION
        $parts = $version.Split('.')
        $patch = [int]$parts[2] + 1
        $newVersion = "$($parts[0]).$($parts[1]).$patch"
        Set-Content VERSION $newVersion
        echo "version=$newVersion" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
      shell: pwsh

    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
        if (-not (Test-Path "C:\ProgramData\Chocolatey")) {
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
        }
      shell: pwsh

    - name: Create dist Directory
      run: |
        New-Item -ItemType Directory -Path ./dist -Force
      shell: pwsh

    - name: Build Scrutiny Package
      run: |
        if (-not (Test-Path ./packages/scrutiny/scrutiny.nuspec)) { throw "scrutiny.nuspec not found" }
        choco pack ./packages/scrutiny/scrutiny.nuspec --outputdirectory ./dist
        if (-not (Test-Path ./dist/scrutiny.*.nupkg)) { throw "Scrutiny package not created" }
      shell: pwsh

    - name: Build ExplorerPatcher Package
      run: |
        if (-not (Test-Path ./packages/explorerpatcher/explorerpatcher.nuspec)) { throw "explorerpatcher.nuspec not found" }
        choco pack ./packages/explorerpatcher/explorerpatcher.nuspec --outputdirectory ./dist
        if (-not (Test-Path ./dist/explorerpatcher.*.nupkg)) { throw "ExplorerPatcher package not created" }
      shell: pwsh

    - name: Configure NuGet Credentials
      run: |
        choco source add -n=GitHubPackages -s="https://nuget.pkg.github.com/LostOnTheLine/index.json" -u="GITHUB_TOKEN" -p="${{ secrets.GITHUB_TOKEN }}"
      shell: pwsh

    - name: Publish to GitHub Packages
      run: |
        $nupkgs = Get-ChildItem -Path ./dist -Filter *.nupkg
        if ($nupkgs.Count -eq 0) { throw "No .nupkg files found in dist/" }
        foreach ($nupkg in $nupkgs) {
          choco push $nupkg.FullName --source https://nuget.pkg.github.com/LostOnTheLine/index.json
        }
      shell: pwsh

    - name: Commit Updated VERSION
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add VERSION
        git commit -m "Bump version to ${{ steps.version.outputs.version }}"
        git push
      shell: bash